# Site settings
title: Big Jay's Fat Ass 6/12-Hour Race
email: ancker@ancker.net
description: The Jekyll version of the Highlights theme by HTML5 UP.
baseurl: "/fatass12hour.com" # the subpath of your site, e.g. /blog
url: "https://ancker010.github.io" # the base hostname & protocol for your site

# Social settings
#500px_url:
#facebook_url: https://facebook.com
#github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
